export const spreadsheets = [
  {
    id: "1",
    title: "Planilha Orçamentária",
    description:
      "Controle e organização de custos, categorias financeiras e projeções orçamentárias do projeto.",
    status: "Em elaboração",
    category: "Financeiro",
    updatedAt: "11/03/2026",
    rows: [
      {
        item: "Direção de Produção",
        categoria: "Equipe técnica",
        quantidade: 1,
        valorUnitario: 4500,
        subtotal: 4500,
        status: "Conferido",
      },
      {
        item: "Produção Executiva",
        categoria: "Equipe técnica",
        quantidade: 1,
        valorUnitario: 4000,
        subtotal: 4000,
        status: "Conferido",
      },
      {
        item: "Assessoria de Comunicação",
        categoria: "Comunicação",
        quantidade: 1,
        valorUnitario: 3500,
        subtotal: 3500,
        status: "Em revisão",
      },
      {
        item: "Custos Administrativos e Logísticos",
        categoria: "Operacional",
        quantidade: 1,
        valorUnitario: 7000,
        subtotal: 7000,
        status: "Conferido",
      },
      {
        item: "Impulsionamento e materiais gráficos",
        categoria: "Divulgação",
        quantidade: 1,
        valorUnitario: 2200,
        subtotal: 2200,
        status: "Pendente",
      },
      {
        item: "Cachês artísticos",
        categoria: "Artístico",
        quantidade: 3,
        valorUnitario: 2000,
        subtotal: 6000,
        status: "Pendente",
      },
    ],
    versions: [
      {
        versao: "v1.0",
        data: "11/03/2026",
        responsavel: "Administração do sistema",
        observacao: "Estrutura inicial do módulo criada.",
      },
      {
        versao: "v1.1",
        data: "11/03/2026",
        responsavel: "Administração do sistema",
        observacao: "Layout do painel e navegação habilitados.",
      },
      {
        versao: "v1.2",
        data: "11/03/2026",
        responsavel: "Administração do sistema",
        observacao: "Página de detalhe expandida com visão de planilha.",
      },
    ],
    documents: [
      {
        nome: "Relatório Técnico.pdf",
        tipo: "PDF",
        atualizacao: "11/03/2026",
      },
      {
        nome: "Cronograma Geral.xlsx",
        tipo: "Planilha",
        atualizacao: "11/03/2026",
      },
      {
        nome: "Comprovantes.zip",
        tipo: "Arquivo compactado",
        atualizacao: "10/03/2026",
      },
    ],
  },
  {
    id: "2",
    title: "Cronograma de Execução",
    description:
      "Planejamento temporal das etapas do projeto, com acompanhamento das ações previstas.",
    status: "Em elaboração",
    category: "Gestão",
    updatedAt: "11/03/2026",
    rows: [
      {
        item: "Pré-produção",
        categoria: "Fase",
        quantidade: 2,
        valorUnitario: 1,
        subtotal: 2,
        status: "Concluído",
      },
      {
        item: "Produção",
        categoria: "Fase",
        quantidade: 2,
        valorUnitario: 1,
        subtotal: 2,
        status: "Em andamento",
      },
      {
        item: "Pós-produção",
        categoria: "Fase",
        quantidade: 3,
        valorUnitario: 1,
        subtotal: 3,
        status: "Pendente",
      },
      {
        item: "Plano de comunicação",
        categoria: "Entrega",
        quantidade: 12,
        valorUnitario: 1,
        subtotal: 12,
        status: "Em andamento",
      },
    ],
    versions: [
      {
        versao: "v1.0",
        data: "11/03/2026",
        responsavel: "Coordenação",
        observacao: "Cronograma inicial criado.",
      },
      {
        versao: "v1.1",
        data: "11/03/2026",
        responsavel: "Coordenação",
        observacao: "Etapas redistribuídas por fase.",
      },
    ],
    documents: [
      {
        nome: "Cronograma Macro.pdf",
        tipo: "PDF",
        atualizacao: "11/03/2026",
      },
      {
        nome: "Etapas.xlsx",
        tipo: "Planilha",
        atualizacao: "10/03/2026",
      },
    ],
  },
  {
    id: "3",
    title: "Relatório de Prestação de Contas",
    description:
      "Consolidação de dados e documentos para prestação de contas e monitoramento da execução.",
    status: "Em elaboração",
    category: "Compliance",
    updatedAt: "11/03/2026",
    rows: [
      {
        item: "Comprovantes financeiros",
        categoria: "Prestação",
        quantidade: 18,
        valorUnitario: 1,
        subtotal: 18,
        status: "Em revisão",
      },
      {
        item: "Relatório técnico",
        categoria: "Prestação",
        quantidade: 1,
        valorUnitario: 1,
        subtotal: 1,
        status: "Pendente",
      },
      {
        item: "Ata de encerramento",
        categoria: "Prestação",
        quantidade: 1,
        valorUnitario: 1,
        subtotal: 1,
        status: "Pendente",
      },
      {
        item: "Anexos comprobatórios",
        categoria: "Prestação",
        quantidade: 24,
        valorUnitario: 1,
        subtotal: 24,
        status: "Em revisão",
      },
    ],
    versions: [
      {
        versao: "v1.0",
        data: "11/03/2026",
        responsavel: "Compliance",
        observacao: "Estrutura inicial da prestação criada.",
      },
    ],
    documents: [
      {
        nome: "Relatório Consolidado.pdf",
        tipo: "PDF",
        atualizacao: "11/03/2026",
      },
      {
        nome: "Notas Fiscais.zip",
        tipo: "Arquivo compactado",
        atualizacao: "11/03/2026",
      },
    ],
  },
  {
    id: "4",
    title: "Mapa de Entregáveis",
    description:
      "Visão geral dos produtos, documentos e marcos de acompanhamento do projeto.",
    status: "Em elaboração",
    category: "Planejamento",
    updatedAt: "11/03/2026",
    rows: [
      {
        item: "Identidade visual",
        categoria: "Entregável",
        quantidade: 1,
        valorUnitario: 1,
        subtotal: 1,
        status: "Concluído",
      },
      {
        item: "Teaser",
        categoria: "Entregável",
        quantidade: 1,
        valorUnitario: 1,
        subtotal: 1,
        status: "Em andamento",
      },
      {
        item: "Making of",
        categoria: "Entregável",
        quantidade: 1,
        valorUnitario: 1,
        subtotal: 1,
        status: "Pendente",
      },
      {
        item: "Book fotográfico",
        categoria: "Entregável",
        quantidade: 1,
        valorUnitario: 1,
        subtotal: 1,
        status: "Pendente",
      },
    ],
    versions: [
      {
        versao: "v1.0",
        data: "11/03/2026",
        responsavel: "Planejamento",
        observacao: "Mapa inicial de entregas estruturado.",
      },
    ],
    documents: [
      {
        nome: "Mapa Geral.pdf",
        tipo: "PDF",
        atualizacao: "11/03/2026",
      },
    ],
  },
];
